# Generated by Django 3.0.2 on 2020-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0002_auto_20200426_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
