# Generated by Django 3.0.2 on 2020-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0003_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='jDV5q37rGlg', max_length=30),
        ),
    ]
