# Generated by Django 3.0.2 on 2020-04-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0004_auto_20200426_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
