# Generated by Django 3.0.2 on 2020-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0006_auto_20200428_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
