# Generated by Django 3.0.2 on 2020-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0007_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
