# Generated by Django 3.0.2 on 2020-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0009_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description1',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle1',
            field=models.TextField(default='default', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle2',
            field=models.TextField(default='default', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
