# Generated by Django 3.0.2 on 2020-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_logo',
            field=models.FileField(default='dog.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
