# Generated by Django 3.0.2 on 2020-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.FileField(default='', upload_to='Posts/resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_logo',
            field=models.FileField(upload_to='Posts/Thumbnails/'),
        ),
    ]
