# Generated by Django 3.0.2 on 2020-05-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200503_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Posts/resumes/'),
        ),
    ]
